language: php

php:
  - 7.1.10

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

install:
  - composer install

before_script:
  - cp .env.example .env
  - mysql -e 'create database 412shop;'
  - export DB_DATABASE='412shop'
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - php artisan migrate --seed --force

script: 
  - php artisan migrate:refresh --seed
  - phpunit

branches:
  only:
    - master
    - develop
